# Generated by Django 3.0.6 on 2020-05-20 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
