# Generated by Django 3.0.6 on 2020-05-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='short_name',
            field=models.CharField(max_length=50),
        ),
    ]
