# Generated by Django 3.0.7 on 2020-07-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='good_reputation',
            field=models.BooleanField(default=False),
        ),
    ]
